name: dev_rpg
description: Become a tech lead, slay bugs, and don't get fired.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  # For Google I/O we are being very specific about pinning to specific branch revision.
  # This is flutter commit hash b593f5167bce84fb3cad5c258477bf3abc1b14eb, tagged
  # as Flutter version 1.5.4.
  sdk: ">=2.3.0-dev.0.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: any
  provider: ^2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flare_flutter: ^1.8.3
  auto_size_text: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  logging: ^0.11.3+2
  git: ^0.5.1+1
  t_stats: ^2.0.0
  test: ^1.6.1


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/style_sphinx/
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/flare/
    - assets/docs/code_chomper_alpha.dart
    - assets/docs/code_chomper_beta.dart

  fonts:
      - family: SpaceMonoRegular
        fonts:
          - asset: assets/fonts/SpaceMono-Regular.ttf
      - family: SpaceMonoBold
        fonts:
          - asset: assets/fonts/SpaceMono-Bold.ttf
      - family: RobotoCondensedBold
        fonts:
          - asset: assets/fonts/RobotoCondensed-Bold.ttf
      - family: RobotoRegular
        fonts:
          - asset: assets/fonts/Roboto-Regular.ttf
      - family: MontserratMedium
        fonts:
          - asset: assets/fonts/Montserrat-Medium.otf
      - family: MontserratRegular
        fonts:
          - asset: assets/fonts/Montserrat-Regular.otf
      - family: MontserratBold
        fonts:
          - asset: assets/fonts/Montserrat-Bold.otf
